title: MeToo Movement Impact Analysis
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Has the MeToo movement affected the representation of women in the newspapers?
baseurl: "/datastory" # the subpath of your site, e.g. /blog
url: "https://josephinepotdevin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  josephinepotdevin

# Build settings
theme: jekyll-theme-cayman
